version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
        - mongodb_network
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin    
       
  mongo-express:
    image: mongo-express
    container_name: mongoExpress
    restart: always
    networks:
      - mongodb_network
    ports:
      - 8081:8081
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
      - 'ME_CONFIG_MONGODB_PORT=27017'
      #- 'ME_CONFIG_MONGODB_ENABLE_ADMIN=false'        
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin   
    #links: 
    #  - mongodb
    #depends_on:
    #   - mongodb
       
       
volumes:
  data: {}

networks:
  mongodb_network:
    driver: bridge
  