version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
        - mongodb_network
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    #command: mongosh -u root -p admin
       
  mongo-express:
    image: mongo-express
    container_name: mongoExpress
    #restart: always
    networks:
      - mongodb_network
    ports:
      - 8080:8081
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
      - 'ME_CONFIG_MONGODB_PORT=27017'
      #- 'ME_CONFIG_MONGODB_ENABLE_ADMIN=false'        
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      #- 'ME_CONFIG_MONGODB_AUTH_USERNAME=root'
      #- 'ME_CONFIG_MONGODB_AUTH_PASSWORD=admin'
      #- ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      #- ME_CONFIG_BASICAUTH_USERNAME=
      #- ME_CONFIG_MONGODB_URL=mongodb://root:admin@mongo:27017"
      #- 'ME_CONFIG_SERVER=localhost'
    links: 
      - mongodb
    depends_on:
       - mongodb
       
       
volumes:
  data: {}

networks:
  mongodb_network:
    driver: bridge
  